name = "java"
title = "Java"
intersphinx = ["https://mongodb.com/docs/manual/objects.inv",
               "https://mongodb.com/docs/drivers/objects.inv"]
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/fundamentals/builders",
    "/usage-examples"
]

[constants]
version = 4.3
full-version = "{+version+}.4"
package-name-org = "mongodb-org"
api = "https://mongodb.github.io/mongo-java-driver/{+version+}"
stable-api = "Stable API"
